### ISSUE TITLE
sms share icon

### ISSUE THREAD

**Issue by atlochowski** [martonmiklos/harbour-sms-share-plugin#11]
what you will say for icon like this? https://www.dropbox.com/s/24nuaz80ovhgegp/icon-m-share-sms.svg?dl=0
It's looking more like other icons in sharing menu. I made it yellow to looks different from mms icon.

**Comment by martonmiklos** [comment]
Hi @atlochowski 
I like it pretty much, added it. I have not released on openrepos yet, I would like to iron out the translation issues first:
https://together.jolla.com/question/193895/transfer-engine-localisation-problem/
